### ISSUE TITLE
Process graph integration

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-udf#1]
I'm looking at the integration of this reference implementation in our Python client and GeoPySpark backend.
To do this, I need to integrate this type of UDF into OpenEO process graphs, so I'm trying to follow the approach described here:
https://open-eo.github.io/openeo-api/udfs/index.html
In Python client code, this becomes:
```
s2_radio = session.imagecollection("SENTINEL2_RADIOMETRY_10M")

        dir = os.path.dirname(openeo_udf.functions.__file__)
        file_name = os.path.join(dir, "raster_collections_ndvi.py")
        udf_code = UdfCode(language="python", source=open(file_name, "r").read())

        ndvi_coverage = s2_radio.apply_tiles( udf_code)
```

The resulting process graph looks like:
```
{'process_graph': {
  'process_id': 'apply_tiles',
  'args': {
    'imagery': {
      'collection_id': 'SENTINEL2_RADIOMETRY_10M'
    },
    'code': {
      'language': 'python',
      'source': '# -*- coding: utf-8 -*-\n# Uncomment the import only for coding support\n#import numpy\n#import pandas\n#import torch\n#import torchvision\n#import tensorflow\n#import tensorboard\n#from openeo_udf.api.base import SpatialExtent, RasterCollectionTile, FeatureCollectionTile, UdfData\n\n__license__ = "Apache License, Version 2.0"\n__author__ = "Soeren Gebbert"\n__copyright__ = "Copyright 2018, Soeren Gebbert"\n__maintainer__ = "Soeren Gebbert"\n__email__ = "soerengebbert@googlemail.com"\n\n\ndef rct_ndvi(udf_data):\n    """Compute the NDVI based on RED and NIR tiles\n\n    Tiles with ids "red" and "nir" are required. The NDVI computation will be applied\n    to all time stamped 2D raster tiles that have equal time stamps.\n\n    Args:\n        udf_data (UdfData): The UDF data object that contains raster and vector tiles\n\n    Returns:\n        This function will not return anything, the UdfData object "udf_data" must be used to store the resulting\n        data.\n\n    """\n    red = None\n    nir = None\n\n    # Iterate over each tile\n    for tile in udf_data.raster_collection_tiles:\n        if "red" in tile.id.lower():\n            red = tile\n        if "nir" in tile.id.lower():\n            nir = tile\n    if red is None:\n        raise Exception("Red raster collection tile is missing in input")\n    if nir is None:\n        raise Exception("Nir raster collection tile is missing in input")\n    if red.start_times is None or red.start_times.tolist() == nir.start_times.tolist():\n        # Compute the NDVI\n        ndvi = (nir.data - red.data) / (nir.data + red.data)\n        # Create the new raster collection tile\n        rct = RasterCollectionTile(id="ndvi", extent=red.extent, data=ndvi,\n                                   start_times=red.start_times, end_times=red.end_times)\n        # Insert the new tiles as list of raster collection tiles in the input object. The new tiles will\n        # replace the original input tiles.\n        udf_data.set_raster_collection_tiles([rct,])\n    else:\n        raise Exception("Time stamps are not equal")\n\n\n# This function call is the entry point for the UDF.\n# The caller will provide all required data in the **data** object.\nrct_ndvi(data)\n'
                                                              }
                                                     }
                                            }
                          }
```
I still need to see if I can also make this work on the backend, but would be good to know if this is what you are envisioning.

**Comment by huhabla** [comment]
Dear Jeroen,
you use the UdfCode schema from the UDF test server that i have
implemented. The server is designed as stand alone system for testing or
backend operations, not related to the OpenEO process graph API. I just
implemented it to have a general swagger description of the datatypes used
for processing independent from the chosen programming language.
You can use the UDF server to test your Python code or as stand-alone
service for your backend. If you use the UDF server, then all the data must
be converted into JSON to be processed.

You can use the udf executable as well in your backend. Then your data must
be available in a GDAL/OGR readable format.

Best regards
Sören

2018-06-05 11:26 GMT+02:00 Jeroen Dries <notifications@github.com>:

**Comment by jdries** [comment]
But we do have to agree on a single type of UDF function interface that we want to support, right? So an example UDF like this one:
https://github.com/Open-EO/openeo-udf/blob/master/src/openeo_udf/functions/raster_collections_ndvi.py
Should work on all of the backends that support running Python? Which implies that a class like RasterCollectionTile should be an integral part of the OpenEO core API? (Or at least the Python UDF Profile of the API?)

**Comment by m-mohr** [comment]
We should have a single interface across back-ends and programming languages at best, of course. That's why I started this [issue](https://github.com/Open-EO/openeo-api/issues/87). At the moment everything related to UDFs is mostly ideas and practical approaches from different perspectives, but nothing has been fixed or is interoperable in any shape or form.

**Comment by jdries** [comment]
Hi Sören, thanks for the explanation. You did a great job on building and documenting this reference implementation by the way!
I indeed don't really need to use UdfCode object in the client, that way I also avoid introducing a dependency which is not really necessary.
I'll start with testing the integration in the GeoPySpark backend, which might reveal some other details.

**Comment by jdries** [comment]
Closing old issue, seems to be solved as I managed to integrate udf's.
