### ISSUE TITLE
Documentation links removed

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-udf#12]
Hey @huhabla,

why did you remove the documentation links in commit https://github.com/Open-EO/openeo-udf/commit/b52247a21bc181b50e8739b9fea7dcdd03773a6b#diff-88b99bb28683bd5b7e3a204826ead112 ?

Now people are complaining that they can't find the docs. Please add them again.

**Comment by huhabla** [comment]
This is an accident. A copy paste mistake, since the links were not present in the index.rst of the documentation located in docs. I fix this.

**Comment by m-mohr** [comment]
Okay, thanks. Why are there two files with the same content anyway?

**Comment by huhabla** [comment]
There are two documentation files in the Python project:

README.rst that is shown in the github website as documentation and the index.rst in the docs directory. I will modify the docs/index.rst to include the README.rst file to avoid differences between them.

**Comment by m-mohr** [comment]
Thanks.
