### ISSUE TITLE
Publishing the Swagger file

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-udf#2]
In the Readme file a Swagger definition is mentioned, but I can't find it in this repository. I'd like to explore it using one of the UIs (Swagger UI or so). Where can I find it?

**Comment by huhabla** [comment]
From the README:

    They are documented in the swagger 2.0 API description that is provided by the UDF test server. 
    However, the Python file that defines the swagger description is available here:

    - https://github.com/Open-EO/openeo-udf/blob/master/src/openeo_udf/server/definitions.py

The swagger file is generated on the fly based on the UDF test server implementation. The python file that defines the swagger description is listed above. To get the swagger file, you need to run the UDF test server:

    (openeo_venv) user@t61:~/src/openeo/openeo-udf$ run_udf_server &
     * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
     * Restarting with stat
     * Debugger is active!
     * Debugger PIN: 599-505-987
    127.0.0.1 - - [13/Jun/2018 10:07:33] "GET /api/v0/swagger.json HTTP/1.1" 200 -

Then download the file:

    wget http://localhost:5000/api/v0/swagger.json

I will update the documentation accordingly.

**Comment by huhabla** [comment]
If you have deployed the docker container, then you can download the swagger description as:

    wget http://localhost:5000/api/v0/swagger.json

Or you can directly access the rendered API documentation with your browser:

    firefox http://localhost/api_docs/index.html

**Comment by m-mohr** [comment]
Thanks, Sören! That is helping me for now, but in the long run we should consider publishing it without requiring to install everything. We could use TravisCI to build the documentation and host it using GitHub pages.
