### ISSUE TITLE
Access to the new data model

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-udf#20]
I realized that the model has been updated and I wanted to have a look at the changes. The new data model, which I assume, is contained in the branch `develop`. I even managed to build the new docker image and get it to run. 

I had to look inside the container for the correct ports. 5000 and 80 are used, with 80 containing the general documentation (outdated, except the somehow cryptic Python code documentation) and 5000 being the port for the processing service.

With this in mind:
* http://localhost:5000/openapi.json contains neither paths nor models
* the api documentations http://localhost:5000/docs and http://localhost:5000/redoc are hence empty

 Is it possible either to fix this, provide an `openapi.json` in order to see the changes in a non Python way or example JSONs for the `DataCube` objects?

**Comment by huhabla** [comment]
I can reproduce this issue and try to fix it.

**Comment by huhabla** [comment]
The issue should be fixed.

Within the source tree there are several examples of the new data model:
https://github.com/Open-EO/openeo-udf/tree/fastapi/src/openeo_udf/server/data_model/examples

**Comment by flahn** [comment]
Perfect! It works now. Thanks for the quick fix.
