### ISSUE TITLE
building/packaging problem: no git tags while using pyscaffold

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-udf#23]
openeo-udf uses pyscaffold, which uses  git tags to determine the package version when building.

But at the moment there are 0 tags in the github repo: https://github.com/Open-EO/openeo-udf/tags, so I when I  build/install the project from source I have a package with  unhelpful version like `0.0.post0.dev450+ge2fc2c1`

For example: openeo-python-driver currently requires `openeo_udf>=0.0.9.post0`, which I can not fulfill with a build from source.

**Comment by soxofaan** [comment]
@jdries   I guess you did the packaging of 0.0.9.post0 which is available in artifactory:
https://artifactory.vgt.vito.be/python-openeo/openeo_udf/0.0.9/openeo_udf-0.0.9.post0.dev2+gb08c63e-py2.py3-none-any.whl

I guess the tag should point to b08c63e

**Comment by jdries** [comment]
To prepare for 1.0, I'm creating release candidates, and tags are there as well!
