### ISSUE TITLE
Unneeded dependency on flask in API classes

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-udf#5]
I use the openeo-udf api classes in my backend, but CI gives an error because flask can not be imported:
https://travis-ci.org/Open-EO/openeo-geopyspark-driver/jobs/392660203

I believe this import:
from flask import json
can simply be removed, or replaced with 'import json'.
(If desirable, I can commit this myself.)

**Comment by huhabla** [comment]
Done.
