### ISSUE TITLE
Publishing the documentation to GitHub pages

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-udf#6]
Hi Sören,

thank you for the impressive presentation today. The documentation looks very nice. Unfortunately, it is not too easy to read them as interested people need to generate it on their own. It is definately possible to do so, but it would be much easier to dig into it if it would be published readily generated on GitHub pages. As you have the Docker container anyway, it think it could be easy to use it to generate the API docs using Travis CI and publish them on GitHub pages. Then people could directly refer to it.

Thank you!

**Comment by m-mohr** [comment]
Any news on this, @huhabla?

**Comment by huhabla** [comment]
I was not able to get the Travis CI running.  The following error occurred:
Could not copy /home/travis/build/Open-EO/openeo-udf/page.
failed to deploy

**Comment by huhabla** [comment]
The problem is, that i have no idea howto configure that correctly. This is the last build:
https://travis-ci.org/Open-EO/openeo-udf/builds/418609935

**Comment by m-mohr** [comment]
I think I fixed the error, was a missing setting (skip-cleanup) in the .travis.yml.

**Comment by m-mohr** [comment]
Seems impossible to run the container on windows so can't debug what's going on, sorry.

**Comment by m-mohr** [comment]
Fixed it - finally.

Links to the docs:
- https://open-eo.github.io/openeo-udf/
- https://open-eo.github.io/openeo-udf/api_docs/

@huhabla Is there anything else generated, which could be interesting to users and is not listed yet?

Took longer than expected as the docker image doesn't seem to run on Windows, at least I can't get it working.

**Comment by m-mohr** [comment]
The build is broken again due to "The command "docker build -t openeo_udf ." failed and exited with 1 during .", see the CI log. This should be fixed again.

**Comment by m-mohr** [comment]
Still failing so documentation doesn't get updated!

**Comment by huhabla** [comment]
The docker image should work again, the API docs are generated.

**Comment by m-mohr** [comment]
@huhabla It still throws errors in CI, I just restarted the build process:
* It seems it can't fetch some dependencies at https://travis-ci.org/Open-EO/openeo-udf/jobs/506022985#L4059
* Then it can't fire up the UDF server at https://travis-ci.org/Open-EO/openeo-udf/jobs/506022985#L4192
* As a consequence, there is a JSON error at https://travis-ci.org/Open-EO/openeo-udf/jobs/506022985#L4319
* Now it seems the CI is stuck and waiting for something, probably until the machine is forced to terminate by Travis after 50mins.

**Comment by huhabla** [comment]
Seems to be solved now.

**Comment by m-mohr** [comment]
Thanks, great!
